import type { AbilityEffectEntry } from '../ability-effects';

/** Ability effects for Imperium factions: SM, GK, IA, IK, Custodes, Sororitas, Mechanicus, Militarum */
export const IMPERIUM_ABILITY_EFFECTS: Record<string, AbilityEffectEntry> = {
  Abomination: { side: 'defensive', activation: 'always', modifiers: { feelNoPain: 2 } },
  'Achillan Eye': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollWounds: 'all' },
    combatType: 'ranged',
  },
  'Advanced Firepower': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { lethalHits: true },
    combatType: 'ranged',
  },
  'Alchemyk Counteragents': {
    side: 'defensive',
    activation: 'always',
    modifiers: { feelNoPain: 6 },
  },
  'An Honourable Death in Combat': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { sustainedHits: 1 },
  },
  'Angelic Visage': {
    side: 'defensive',
    activation: 'always',
    modifiers: { hitModifier: -1 },
    combatType: 'melee',
  },
  Annihilator: {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollWounds: 'all' },
    combatType: 'ranged',
  },
  'Annihilator Protocols': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { sustainedHits: 2 },
    combatType: 'melee',
  },
  'Aquilon Optics': {
    side: 'offensive',
    activation: 'always',
    modifiers: { rerollHits: 'ones', rerollWounds: 'ones' },
  },
  'Armoured Resilience': {
    side: 'defensive',
    activation: 'always',
    modifiers: { damageReduction: 1 },
  },
  'Armoured Spearhead': {
    side: 'offensive',
    activation: 'always',
    modifiers: { rerollHits: 'ones' },
  },
  'Astartes shield': {
    side: 'defensive',
    activation: 'always',
    modifiers: { invulnerableSave: 4 },
  },
  'Attuned Onslaught': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { damageBonus: 1 },
    combatType: 'melee',
  },
  'Auspex Array': {
    side: 'offensive',
    activation: 'always',
    modifiers: { ignoresCover: true },
    combatType: 'ranged',
  },
  'Automated Defences': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { hitModifier: 1 },
    combatType: 'ranged',
  },
  'Ballistus Strike': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollHits: 'all' },
    combatType: 'ranged',
  },
  'Battle-lust': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { bonusAttacks: 2 },
    combatType: 'melee',
  },
  'Blistering Salvoes': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { hitModifier: 1 },
    combatType: 'ranged',
  },
  'Breaching Command': {
    side: 'offensive',
    activation: 'always',
    modifiers: { rerollHits: 'ones' },
  },
  'Breaching Team': {
    side: 'offensive',
    activation: 'always',
    modifiers: { rerollWounds: 'ones' },
  },
  'Bring it Down!': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollHits: 'ones', rerollWounds: 'ones' },
    combatType: 'ranged',
  },
  'CAT Unit': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { ignoresCover: true },
    combatType: 'ranged',
  },
  'Cadia Stands!': {
    side: 'defensive',
    activation: 'conditional',
    modifiers: { grantsBenefitOfCover: true },
  },
  'Catechism of Fire': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { devastatingWounds: true },
    combatType: 'ranged',
  },
  'Champion of the Kingsguard': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollHits: 'all', rerollWounds: 'all' },
    combatType: 'melee',
  },
  'Close-quarters Firepower': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { apImprovement: 1 },
    combatType: 'ranged',
  },
  'Close-quarters Warfare': {
    side: 'offensive',
    activation: 'always',
    modifiers: { ignoreHitPenalties: true },
    combatType: 'ranged',
  },
  'Cold and Calculating': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { lethalHits: true },
  },
  'Cunning Hunters': {
    side: 'offensive',
    activation: 'always',
    modifiers: { rerollWounds: 'ones' },
  },
  'Daughter of the Abyss': {
    side: 'defensive',
    activation: 'always',
    modifiers: { feelNoPain: 3 },
  },
  'Deadly Stalkers': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { woundModifier: 1 },
  },
  'Death Totem': {
    side: 'offensive',
    activation: 'always',
    modifiers: { rerollHits: 'ones' },
    combatType: 'melee',
  },
  'Death to the Alien': {
    side: 'offensive',
    activation: 'always',
    modifiers: { rerollHits: 'ones' },
  },
  Deathwing: { side: 'offensive', activation: 'always', modifiers: { ignoreHitPenalties: true } },
  'Decimator Protocols': {
    side: 'offensive',
    activation: 'always',
    modifiers: { rerollHits: 'ones' },
    combatType: 'ranged',
  },
  'Deft Parry': {
    side: 'defensive',
    activation: 'always',
    modifiers: { hitModifier: -1 },
    combatType: 'melee',
  },
  Destructor: {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { apImprovement: 1 },
    combatType: 'ranged',
  },
  'Duty Eternal': { side: 'defensive', activation: 'always', modifiers: { damageReduction: 1 } },
  'Electro-Infusion': {
    side: 'defensive',
    activation: 'conditional',
    modifiers: { woundModifier: -1 },
  },
  'Embodied Prophecy': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { sustainedHits: 1 },
    combatType: 'melee',
  },
  'Emnity for the Unworthy': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { hitModifier: 1 },
  },
  'Endurant shield': {
    side: 'defensive',
    activation: 'always',
    modifiers: { invulnerableSave: 4 },
  },
  'Exemplar Warrior': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollWounds: 'all' },
  },
  'Eye of Judgement': {
    side: 'offensive',
    activation: 'always',
    modifiers: { rerollWounds: 'all' },
  },
  'Ferocious Assault': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { hitModifier: 1 },
    combatType: 'ranged',
  },
  'Fiend Slayer': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollWounds: 'all' },
  },
  'Flak Battery': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollHits: 'all' },
    combatType: 'ranged',
  },
  Foesight: { side: 'offensive', activation: 'conditional', modifiers: { rerollHits: 'all' } },
  'Force Edge': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { apImprovement: 1 },
    combatType: 'melee',
  },
  'Fortis Doctrines': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { hitModifier: 1 },
  },
  'Galatus Shield': {
    side: 'defensive',
    activation: 'always',
    modifiers: { woundModifier: -1 },
    combatType: 'melee',
  },
  'Grim Demeanour': { side: 'offensive', activation: 'conditional', modifiers: { hitModifier: 1 } },
  'Guardian Eternal': {
    side: 'defensive',
    activation: 'always',
    modifiers: { damageReduction: 1 },
  },
  'Gung-ho Executioners': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { hitModifier: 1 },
    combatType: 'ranged',
  },
  'Heavy Assault Infantry': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollWounds: 'ones' },
    combatType: 'ranged',
  },
  'Helix Gauntlet': { side: 'defensive', activation: 'always', modifiers: { feelNoPain: 6 } },
  'Holy Piety': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollHits: 'all' },
    combatType: 'melee',
  },
  'Icon of Obstinacy': {
    side: 'defensive',
    activation: 'conditional',
    modifiers: { woundModifier: -1 },
  },
  'Imperial Law': { side: 'offensive', activation: 'conditional', modifiers: { lethalHits: true } },
  'Impetuous Fervour': {
    side: 'offensive',
    activation: 'always',
    modifiers: { rerollHits: 'ones' },
  },
  'Indomitor Doctrines': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { strengthBonus: 2 },
  },
  'Inner Circle': { side: 'defensive', activation: 'always', modifiers: { damageReduction: 1 } },
  Interceptor: {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { hitModifier: 1 },
    combatType: 'ranged',
  },
  'Judgement of the Omnissiah': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollWounds: 'all' },
    combatType: 'melee',
  },
  'Jungle Fighters': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { woundModifier: 1 },
    combatType: 'melee',
  },
  'Knights of Caliban': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { critWoundOn: 4 },
    combatType: 'melee',
  },
  'Leading the Charge': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { devastatingWounds: true },
    combatType: 'melee',
  },
  'Legendary Tenacity': {
    side: 'defensive',
    activation: 'conditional',
    modifiers: { woundModifier: -1 },
  },
  Lifewards: { side: 'defensive', activation: 'conditional', modifiers: { feelNoPain: 4 } },
  'Lightning-fast Manoeuvres': {
    side: 'defensive',
    activation: 'always',
    modifiers: { hitModifier: -1 },
    combatType: 'ranged',
  },
  'Line-breaker': {
    side: 'offensive',
    activation: 'always',
    modifiers: { ignoreHitPenalties: true },
    combatType: 'ranged',
  },
  'Mark the Target': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { devastatingWounds: true },
    combatType: 'ranged',
  },
  'Mass of Doom': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { devastatingWounds: true },
    combatType: 'melee',
  },
  'Masters of Close Confines': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { lethalHits: true },
    combatType: 'ranged',
  },
  'Merciless Hunter': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { woundModifier: 1 },
    combatType: 'ranged',
  },
  'Merciless Judgement': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { woundModifier: 1 },
    combatType: 'ranged',
  },
  'Micromelta Round': {
    side: 'offensive',
    activation: 'always',
    modifiers: { critWoundOn: 4 },
    combatType: 'ranged',
  },
  'Might of Titan': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { bonusAttacks: 3, strengthBonus: 3 },
    combatType: 'melee',
  },
  'Ministorum Sermon': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { woundModifier: 1 },
    combatType: 'melee',
  },
  'Mobile Hunter-killers': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollWounds: 'all' },
  },
  'Mow Down the Enemy': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { devastatingWounds: true },
    combatType: 'ranged',
  },
  'Null Rod': { side: 'defensive', activation: 'always', modifiers: { feelNoPain: 4 } },
  Omnispex: {
    side: 'offensive',
    activation: 'always',
    modifiers: { ignoresCover: true },
    combatType: 'ranged',
  },
  'Overseer of Redemption': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollHits: 'all', rerollWounds: 'all' },
    combatType: 'melee',
  },
  'Point-blank Barrage': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { apImprovement: 1 },
    combatType: 'ranged',
  },
  'Press the Attack': { side: 'offensive', activation: 'always', modifiers: { sustainedHits: 1 } },
  'Purity of Execution': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { devastatingWounds: true },
    combatType: 'ranged',
  },
  'Rearm, Reload, Fire': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { sustainedHits: 1 },
    combatType: 'ranged',
  },
  'Refractor Field': {
    side: 'defensive',
    activation: 'always',
    modifiers: { invulnerableSave: 5 },
  },
  'Refuse to Yield': { side: 'defensive', activation: 'always', modifiers: { damageReduction: 1 } },
  'Resolute Will': {
    side: 'defensive',
    activation: 'conditional',
    modifiers: { woundModifier: -1 },
  },
  'Righteous Paragons': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { hitModifier: 1, woundModifier: 1 },
  },
  'Rituale Nullificatus': { side: 'defensive', activation: 'always', modifiers: { feelNoPain: 4 } },
  'Rod of Office': { side: 'offensive', activation: 'always', modifiers: { rerollHits: 'ones' } },
  'Rotating Death': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { sustainedHits: 2 },
    combatType: 'ranged',
  },
  'Rugged Resilience': {
    side: 'defensive',
    activation: 'conditional',
    modifiers: { woundModifier: -1 },
  },
  'Sanctity of Purpose': {
    side: 'offensive',
    activation: 'always',
    modifiers: { rerollWounds: 'ones' },
  },
  'Searing Conflagaration': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollWounds: 'ones' },
    combatType: 'ranged',
  },
  'Shield Dome': { side: 'defensive', activation: 'always', modifiers: { invulnerableSave: 5 } },
  'Shock Assault': {
    side: 'offensive',
    activation: 'always',
    modifiers: { rerollWounds: 'ones' },
    combatType: 'melee',
  },
  'Siege Captain': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { strengthBonus: 2, apImprovement: 2, damageBonus: 2 },
  },
  Signum: {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { ignoresCover: true },
    combatType: 'ranged',
  },
  'Slayers of Tyrants': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollWounds: 'all' },
  },
  'Soulguilt scanner': {
    side: 'offensive',
    activation: 'always',
    modifiers: { ignoresCover: true },
    combatType: 'ranged',
  },
  'Stand Vigil': { side: 'offensive', activation: 'always', modifiers: { rerollWounds: 'ones' } },
  'Storm Shield': { side: 'defensive', activation: 'always', modifiers: { invulnerableSave: 4 } },
  'Storm Troopers': {
    side: 'offensive',
    activation: 'always',
    modifiers: { rerollWounds: 'ones' },
  },
  'Storm of Retribution': {
    side: 'offensive',
    activation: 'always',
    modifiers: { rerollHits: 'ones', rerollWounds: 'ones' },
    combatType: 'ranged',
  },
  'Strafing Run': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { hitModifier: 1 },
    combatType: 'ranged',
  },
  'Surge of Wrath': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollHits: 'all', rerollWounds: 'all' },
    combatType: 'melee',
  },
  'Sworn Protectors': {
    side: 'defensive',
    activation: 'conditional',
    modifiers: { woundModifier: -1 },
  },
  'Talonstrike Doctrines': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { apImprovement: 1, lance: true },
  },
  'Tanith Camo-cloaks': {
    side: 'defensive',
    activation: 'always',
    modifiers: { grantsBenefitOfCover: true },
  },
  'Tank-killer': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollWounds: 'all' },
    combatType: 'ranged',
  },
  'Target Elimination': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { bonusAttacks: 2 },
    combatType: 'ranged',
    weaponScope: { weaponNameIncludes: 'bolt' },
  },
  'Targeter Optics': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { ignoresCover: true },
    combatType: 'ranged',
  },
  'The Lion Helm': { side: 'defensive', activation: 'always', modifiers: { invulnerableSave: 4 } },
  'The Spiritshield Helm': {
    side: 'defensive',
    activation: 'always',
    modifiers: { feelNoPain: 3 },
  },
  'Threat Level Rising': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { hitModifier: 1 },
  },
  'Thunderous Charge': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { damageBonus: 1 },
    combatType: 'melee',
  },
  'Thunderous Impact': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { strengthBonus: 1, damageBonus: 1 },
    combatType: 'melee',
  },
  'Titan-killer': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { devastatingWounds: true },
    combatType: 'ranged',
  },
  'Total Obliteration': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollHits: 'all', rerollWounds: 'all' },
    combatType: 'ranged',
  },
  'Unbreakable Duty': {
    side: 'defensive',
    activation: 'conditional',
    modifiers: { feelNoPain: 4 },
  },
  'Unyielding in the Face of the Foe': {
    side: 'defensive',
    activation: 'conditional',
    modifiers: { grantsBenefitOfCover: true },
  },
  'Urban Warfare': {
    side: 'defensive',
    activation: 'conditional',
    modifiers: { damageReduction: 1 },
  },
  'Vanguard Assault': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { lethalHits: true },
    combatType: 'melee',
  },
  "Vector of the Omnissiah's Wrath": {
    side: 'offensive',
    activation: 'always',
    modifiers: { ignoresCover: true },
    combatType: 'ranged',
  },
  'Veil of Time': { side: 'offensive', activation: 'always', modifiers: { sustainedHits: 1 } },
  'Vitruous Onslaught': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollWounds: 'ones' },
  },
  'Wall of Muscle': { side: 'defensive', activation: 'always', modifiers: { damageReduction: 1 } },
  'adeptus-custodes::Devoted to Destruction': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { bonusAttacks: 2 },
    combatType: 'melee',
  },
  'imperial-agents::Grey Knights Terminator Squad::Hammerhand': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { lethalHits: true },
    combatType: 'melee',
  },
  'space-marines::Bladeguard Veteran Squad::Bladeguard': {
    side: 'offensive',
    activation: 'conditional',
    modifiers: { rerollHits: 'ones' },
    combatType: 'melee',
  },
};
